spring:
  profiles:
    active:
      - izanamiProd
      - prod
izanami:
  host: "http://localhost:9000"
  clientId: "xxxx"
  clientSecret: "xxxx"
  fallback:
    features: >
      [
        { "id": "izanami:example:emailNotifications", "enabled": false },
        { "id": "izanami:example:deleteAll", "enabled": false }
      ]
    configs: >
      [
        { "id": "izanami:example:config", "value": { "emailProvider": "test" } }
      ]
    experiments: >
      [
        {
          "id": "izanami:example:button",
          "name": "Test button",
          "description": "Test button",
          "enabled": true,
          "variant": {
            "id": "A",
            "name": "Variant A",
            "description": "Variant A"
          }
        }
      ]