---
- type: domains\.Key
  specAsParameter:
    - type: string
- type: java\.time\.LocalDateTime
  specAsParameter:
    - type: string
- type: play\.api\.libs\.json\.jsvalue
  specAsParameter:
    - type: any
- type: play\.api\.libs\.json\.jsobject
  specAsParameter:
    - type: object
- type: string with shapeless\.tag\.tagged
  specAsParameter:
    - type: string
- type: request
  specAsParameter: []
