---
- type: domains\.Key
  specAsParameter:
    - type: string
- type: java\.time\.LocalDateTime
  specAsParameter:
    - type: string
- type: play\.api\.libs\.json\.jsvalue
  specAsParameter:
    - type: object
- type: request
  specAsParameter: []
