spring:
  profiles:
    active:
      - izanamiProd
      - dev
leveldb:
  path: "leveldb/datas"
betaserie:
  apikey: "a8dd8ebe25e9"
  url: "https://api.betaseries.com"
tvdb:
  apikey: "92466265017F27E4"
  url: "https://api.thetvdb.com"
  banner: "https://www.thetvdb.com/banners/"
izanami:
  host: "http://localhost:9000"
  clientId: "xxxx"
  clientSecret: "xxxx"
  fallback:
    features: >
      [
        { "id": "izanami:example:emailNotifications", "enabled": false },
        { "id": "mytvshows:season:markaswatched", "enabled": true },
        { "id": "mytvshows:providers:tvdb", "enabled": false },
        { "id": "mytvshows:providers:betaserie", "enabled": true },
        { "id": "mytvshows:providers:omdb", "enabled": false }
      ]
    configs: >
      [
        { "id": "izanami:example:config", "value": { "emailProvider": "test" } }
      ]
    experiments: >
      [
        {
          "id": "mytvshows:gotoepisodes:button",
          "name": "Test button",
          "description": "Test button",
          "enabled": true,
          "variant": {
            "id": "A",
            "name": "Variant A",
            "description": "Variant A"
          }
        }
      ]