spring:
  profiles:
    active:
      - izanamiDev
      - dev
leveldb:
  path: "leveldb/datas"
tvdb:
  apikey: "92466265017F27E4"
  url: "https://api.thetvdb.com"
  banner: "https://www.thetvdb.com/banners/_cache/"
izanami:
  host: "http://localhost:9000"
  clientId: "xxxx"
  clientSecret: "xxxx"
  fallback:
    features: >
      [
        { "id": "izanami:example:emailNotifications", "enabled": false },
        { "id": "mytvshows:season:markaswatched", "enabled": true }
      ]
    configs: >
      [
        { "id": "izanami:example:config", "value": { "emailProvider": "test" } }
      ]
    experiments: >
      [
        {
          "id": "izanami:example:button",
          "name": "Test button",
          "description": "Test button",
          "enabled": true,
          "variant": {
            "id": "A",
            "name": "Variant A",
            "description": "Variant A"
          }
        }
      ]