version: '2'
services:
  redis:
    image: redis
    ports:
      - 6380:6379
  cassandra:
    image: cassandra:3.11
    ports:
      - 9042:9042
      - 7000:7000
    environment:
      - "CASSANDRA_LISTEN_ADDRESS=127.0.0.1"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    ports:
      - 9210:9200
    environment:
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  mongo:
    image: mongo:3.4
    ports:
      - 27017:27017