version: '2'
services:
  redis:
    image: redis
    ports:
      - 6380:6379
  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - 9220:9200
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
    ports:
      - 9210:9200
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017
  dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
      - "8001:8000"
  postgres_test:
    image: postgres:11.2
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./install_extensions.sh:/docker-entrypoint-initdb.d/install_extensions.sh
    ports:
      - 5555:5432