version: '3'

services:
  keycloak_postgres:
    image: postgres
    volumes:
      - ./keycloak_postgres_data:/var/lib/postgresql/data
      - ./keycloak/https:/etc/x509/https
      - ./keycloak/mtls:/etc/x509/iza-mtls
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  izanami_keycloak:
    image: jboss/keycloak
    ports:
      - 8980:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: izanami
      KEYCLOAK_PASSWORD: izanami
      X509_CA_BUNDLE: /etc/x509/iza-mtls/tls-front.crt
    depends_on:
      - keycloak_postgres