version: '2'
services:
  redis:
    image: redis
    ports:
    - 6379:6379
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
    ports:
      - 9200:9200
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.1
    ports:
    - 32182:32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
    - "moby:127.0.0.1"
    - "localhost: 127.0.0.1"
  kafka:
    image: confluentinc/cp-kafka:3.2.1
    ports:
    - 29092:29092
    depends_on:
    - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
    - "moby:127.0.0.1"
    - "localhost: 127.0.0.1"