[tools]
java = "temurin-21"
sbt = "1.12"
node = "24"

[tasks."install:front"]
dir = "izanami-frontend"
run = "npm install --force && npx playwright install chromium"

[tasks."install:back"]
run = "docker-compose pull && sbt compile"

[tasks.install]
run = [{task = "install:front"}, {task = "install:back"}]

[tasks."dev:containers"]
run = "docker-compose rm -f && docker-compose up"

[tasks.clean]
run = "docker-compose down && docker-compose rm -f"

[tasks."dev:front"]
dir = "izanami-frontend"
run = "npm run dev"

[tasks."dev:back"]
run = "sbt -jvm-debug 5005 \"~run -Dconfig.resource=dev.conf\""
raw=true

[tasks.dev]
run = "process-compose -f ./process-compose.yaml"

[tasks.doc]
dir = "manual"
run = "npm start"

[tasks."test:back"]
run = "sbt \"testOnly *AllTests\""

[tasks."test:front"]
dir = "izanami-frontend"
run = "npm test"

[tasks.tests]
run = [{task = "test:front"}, {task = "test:back"}]