CREATE TYPE IMPORT_STATUS AS ENUM ('PENDING', 'FINISHED', 'FAILED');

CREATE TABLE pending_imports (
    id UUID DEFAULT gen_random_uuid () PRIMARY KEY,
    status IMPORT_STATUS NOT NULL DEFAULT 'PENDING',
    creation TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    result JSON
)