CREATE TYPE GLOBAL_EVENT_TYPES AS ENUM ('TENANT_CREATED', 'TENANT_DELETED');
CREATE TYPE LOCAL_EVENT_TYPES AS ENUM ('FEATURE_CREATED', 'FEATURE_UPDATED', 'FEATURE_DELETED');


CREATE TABLE global_events (
    id bigint PRIMARY KEY DEFAULT nextval('izanami.eventid'),
    event_type GLOBAL_EVENT_TYPES NOT NULL,
    entity_id TEXT NOT NULL,
    event JSONB NOT NULL
);