ALTER TABLE users ADD COLUMN roles jsonb;

UPDATE users SET roles = '[]'::jsonb WHERE user_type='OIDC';

ALTER TABLE users ADD CONSTRAINT roles_is_array CHECK (jsonb_typeof(roles) = 'array');

ALTER TYPE GLOBAL_EVENT_TYPES ADD VALUE 'CONFIGURATION_UPDATED';
ALTER TYPE EVENT_ORIGIN ADD VALUE 'TECHNICAL';
ALTER TYPE AUTHENTICATION ADD VALUE 'IZANAMI';