CREATE TABLE MAILERS(
  name TEXT PRIMARY KEY,
  configuration JSONB NOT NULL DEFAULT '{}'
);

INSERT INTO MAILERS(name) VALUES ('CONSOLE');
INSERT INTO MAILERS(name) VALUES ('MAILJET');
INSERT INTO MAILERS(name) VALUES ('MAILGUN');
INSERT INTO MAILERS(name) VALUES ('SMTP');