version: '3'
services:

  client:
    build: ./client
    networks:
      - bench
    depends_on:
      - izanami

  izanami:
    image: maif/izanami
    ports:
      - 8080:8080
    networks:
      - bench
    depends_on:
      - redis
      - elasticsearch
    environment:
      - INITIAL_APIKEY_CLIENT_ID=apikey
      - INITIAL_APIKEY_CLIENT_SECRET=123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTIC_HOST=elasticsearch
      - IZANAMI_DATABASE=InMemoryWithDb
      - IN_MEMORY_WITH_DB_DB=Redis
      - FEATURE_IMPORT=/data/features.ndjson
    volumes:
      - ./data:/data
  redis:
    image: redis:4.0.8
    networks:
      - bench
    ports:
      - 6379:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    networks:
      - bench
    ports:
      - 9210:9200
    environment:
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
volumes:
  data:

networks:
  bench:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24