name: Load Java and Node version
description: Load Java and Node version
runs:
  using: "composite"
  steps:
    - name: Load Node version
      run: |
        export VERSION=$(cat ${{ github.workspace }}/.nvmrc)
        echo "NODE_VERSION=${VERSION}" >> $GITHUB_ENV
      shell: bash
    - name: Load Java version
      run: |
        export VERSION=$(cat ${{ github.workspace }}/.java-version)
        echo "JAVA_VERSION=${VERSION}" >> $GITHUB_ENV
      shell: bash