include "application.conf"

app {
  secret = "S_iVTvZcJhGxA^jPl2y9FLB/Yfh/OH3j/:ce>xa`wawr44Wufm_H3^u5ln7:tiDn"
  config {
    mode = "dev"
  }
  pg {
    port = 5432
    host = "localhost"
    database = "postgres"
    user = "postgres"
    password = "postgres"
  }
  openid {
    clientId = foo
    clientSecret = bar
    authorizeUrl = "http://localhost:9001/auth"
    tokenUrl = "http://localhost:9001/token"
    redirectUrl = "http://localhost:3000/login"
  }
  admin {
    password = "ADMIN_DEFAULT_PASSWORD"
  }
  exposition {
    url= "http://localhost:3000"
    backend= "http://localhost:9000"
  }
  wasmo {
    url="http://localhost:5001"
    clientId="admin-api-apikey-id"
    clientSecret="admin-api-apikey-secret"
  }
}

play.application.loader = "fr.maif.izanami.IzanamiLoader"