FROM postgres:17.2

RUN set -eux; \
    apt-get update; \
    apt-get install -y default-jre netcat-traditional;

RUN mkdir /app
#RUN groupadd -g 10001 javauser && useradd -u 10000 -g javauser javauser
ENV IZANAMI_CONTAINERIZED=true
COPY ../target/izanami.jar /app/izanami.jar
COPY script.sh /app/script.sh
RUN chmod +x /app/script.sh

#WORKDIR /app
RUN chown -R postgres:postgres /app
#USER postgres
CMD ["/bin/sh", "/app/script.sh"]