name: build-package

on:
  push:
    branches:
      - "**"
      - "!master"
jobs:
  build-package:
    runs-on: ubuntu-latest
    name: "Build server package"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt/boot
            ~/.sbt
            ~/.coursier
            ~/.nvm
            ~/.yarn-cache
            ~/.rustup
            ~/.cargo
          key: ${{ runner.os }}-izanami
      - run: echo "JAVA_OPTS=-Xms2G -Xmx2G -Xss1G -XX:ReservedCodeCacheSize=256m" >> $GITHUB_ENV
      - run: |
          ./scripts/build-javascript.sh
          sbt  -Dsbt.color=always -Dsbt.supershell=false ";izanami-server/assembly;izanami-server/dist;izanami-server/docker:publishLocal;+jvm/publishLocal;izanami-spring/publishLocal"
      - name: clean before cache
        run: |
          find ~/.ivy2 -name "ivydata-*.properties" -print -delete
          find ~/.sbt  -name "*.lock"               -print -delete