name: Publish snapshot
on:
  push:
    branches: [ master ]
jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Build server package and publish it to Central"
            command: ./scripts/build-javascript.sh && ./scripts/sbt-publish.sh
          - name: "Build js client and publish it to npm if needed"
            command: ./scripts/publish-npm.sh
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/load-versions
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt/boot
            ~/.sbt
            ~/.coursier
            ~/.nvm
            ~/.yarn-cache
            ~/.rustup
            ~/.cargo
          key: ${{ runner.os }}-izanami
      - uses: ./.github/workflows/java-opts
      - run: ${{ matrix.command }}
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - uses: ./.github/workflows/clean-cache
