name: publish
on:
  push:
    tags:
      - "v*"
    branches:
      - "master"

jobs:
  publish-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Build server package and publish it to bintray"
            command: ./scripts/build-javascript.sh && ./scripts/sbt-publish.sh
          - name: "Build js client and publish it to npm if needed"
            command: ./scripts/publish-npm.sh
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - run: ${{ matrix.command }}