name: Release and publish
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'release version (1.0.0, v1.2.0, etc)'
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: test  "${{ github.ref }}" = "refs/heads/master" ||  (echo "Release can be created only from master (${{ github.ref }} not supported)." && false)
      - name: get release version (remove "v" of "vX.Y.Z")
        run: |
          export VERSION=$(echo ${{ github.event.inputs.releaseVersion }} | sed 's/v//')
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
      - name: release sbt
        run: |
          git config --local user.email "izanami-github-actions@users.noreply.github.com"
          git config --local user.name "izanami-github-actions"
          sbt "release with-defaults release-version ${{ env.RELEASE_VERSION }}"
  publish-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Build server package and publish it to bintray"
            command: ./scripts/build-javascript.sh && ./scripts/sbt-publish.sh
          - name: "Build js client and publish it to npm if needed"
            command: ./scripts/publish-npm.sh
    name: ${{ matrix.name }}
    needs: create-tag
    steps:
      - name: tag name (add "v" of "X.Y.Z")
        run: |
          export VERSION=$(echo ${{ github.event.inputs.releaseVersion }} | sed 's/v//')
          echo "TAG_NAME=v$VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.TAG_NAME }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt/boot
            ~/.sbt
            ~/.coursier
            ~/.nvm
            ~/.yarn-cache
            ~/.rustup
            ~/.cargo
          key: ${{ runner.os }}-izanami
      - uses: ./.github/workflows/java-opts
      - run: ${{ matrix.command }}
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/workflows/clean-cache
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: publish-job
    steps:
      - name: tag name (add "v" of "X.Y.Z")
        run: |
          export VERSION=$(echo ${{ github.event.inputs.releaseVersion }} | sed 's/v//')
          echo "TAG_NAME=v$VERSION" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
